2018-02-13T10:18:30.691Z - info: Test execution started
2018-02-13T10:18:30.692Z - info: Got following options to run{"testName":"Clean Install","UDID":"cd21ccc5","port":4003,"systemPort":8203,"bpPort":6003,"desCaps":"{\n\"testName\":\"Clean Install\",\n\"groupTest\":false,\n\"desiredCapabilities\": {\n        \"platformName\": \"Android\",\n        \"deviceName\": \"Android\",\n        \"appPackage\":\"com.gorro.nothing\",\n        \"appActivity\":\"com.gorro.nothing.NothingActivity\",\n        \"fullReset\":false,\n        \"newCommandTimeout\":120000,\n        \"skipUnlock\":true\n      }\n\n}\n"}
2018-02-13T10:18:30.720Z - info: Trying to connect to openSTF with serial number cd21ccc5
2018-02-13T10:18:30.768Z - info: executing command adb connect  localhost:7405
2018-02-13T10:18:30.775Z - info: /home/trixo/Downloads/appium-1.8.0-beta3/build/lib/main.js -p 4003 -bp6003  --log-timestamp --log /home/trixo/Code/javaRewrite/log4003.txt
2018-02-13T10:18:30.775Z - info: Trying to create appium Server on port: 4003
2018-02-13T10:18:32.961Z - info: Appium server created on port: 4003
2018-02-13T10:19:03.715Z - info: Running clean Install test with following paramters, appPackage: com.pointvoucher.playlondonpv activityName: com.unity3d.player.UnityPlayerActivity apkFile: /home/trixo/Code/javaRewrite/Tests/CleanInstall/apk/pl.apk
2018-02-13T10:19:06.192Z - info: App exists in device => trying to remove
2018-02-13T10:19:14.248Z - info: App removed
2018-02-13T10:19:14.248Z - info: Installing app to device /home/trixo/Code/javaRewrite/Tests/CleanInstall/apk/pl.apk
2018-02-13T10:22:11.467Z - info: starting package : com.pointvoucher.playlondonpv with activity name: com.unity3d.player.UnityPlayerActivity
2018-02-13T10:22:15.953Z - info: Running fnPermission with number of repeats: 5 and value: true
2018-02-13T10:22:17.392Z - info: Found permission button going to click #0
2018-02-13T10:22:17.392Z - info: Running click event : Click on permission button with 5repets
2018-02-13T10:22:17.392Z - info: Looking for image on screen:Click on permission button with 5 repeats 
2018-02-13T10:22:17.392Z - info: Running delay for : 0
2018-02-13T10:22:17.393Z - info: Running delay for : 0
2018-02-13T10:22:18.693Z - info: Found image on screen: Click on permission button
2018-02-13T10:22:19.009Z - info: clicked on : Click on permission button with following coordinates x=438 y=556.5
2018-02-13T10:22:19.010Z - info: Looking for image on screen:Loading screen with 20 repeats 
2018-02-13T10:22:19.010Z - info: Running delay for : 6000
2018-02-13T10:22:25.012Z - info: Running delay for : 2000
2018-02-13T10:22:28.216Z - info: Running delay for : 2000
2018-02-13T10:22:31.102Z - info: Running delay for : 2000
2018-02-13T10:22:33.978Z - info: Running delay for : 2000
2018-02-13T10:22:36.929Z - info: Running delay for : 2000
2018-02-13T10:22:39.932Z - info: Running delay for : 2000
2018-02-13T10:22:43.029Z - info: Running delay for : 2000
2018-02-13T10:22:45.825Z - info: Running delay for : 2000
2018-02-13T10:22:48.574Z - info: Running delay for : 2000
2018-02-13T10:22:51.910Z - info: Found image on screen: Loading screen
2018-02-13T10:22:51.911Z - info: Test:Clean Install[FINISHED]
2018-02-13T10:38:57.003Z - info: Appium on close  null
2018-02-13T10:38:57.009Z - info: You are not owner localhost:7405 => open STF 
2018-02-13T10:38:57.011Z - info: You are not owner localhost:7405 => open STF 
2018-02-13T10:44:11.056Z - info: Test execution started
2018-02-13T10:44:11.056Z - info: Got following options to run{"testName":"Clean Install","UDID":"cd21ccc5","port":4003,"systemPort":8203,"bpPort":6003,"desCaps":"{\n\"testName\":\"Clean Install\",\n\"groupTest\":false,\n\"desiredCapabilities\": {\n        \"platformName\": \"Android\",\n        \"deviceName\": \"Android\",\n        \"appPackage\":\"com.gorro.nothing\",\n        \"appActivity\":\"com.gorro.nothing.NothingActivity\",\n        \"fullReset\":false,\n        \"newCommandTimeout\":120000,\n        \"skipUnlock\":true\n      }\n\n}\n"}
2018-02-13T10:44:11.085Z - info: Trying to connect to openSTF with serial number cd21ccc5
2018-02-13T10:44:11.134Z - info: executing command adb connect  localhost:7405
2018-02-13T10:44:11.141Z - info: /home/trixo/Downloads/appium-1.8.0-beta3/build/lib/main.js -p 4003 -bp6003  --log-timestamp --log /home/trixo/Code/javaRewrite/log4003.txt
2018-02-13T10:44:11.141Z - info: Trying to create appium Server on port: 4003
2018-02-13T10:44:13.443Z - info: Appium server created on port: 4003
2018-02-13T10:44:18.799Z - info: Appium err 2018-02-13 10:44:18:798 - [ADB] Error: Error finding if app is installed. Original error: No device connected, cannot run adb shell command 'pm list packages io.appium.unlock'
    at Object.wrappedLogger.errorAndThrow (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/appium-support/lib/logging.js:69:13)
    at ADB.callee$0$0$ (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/appium-adb/lib/tools/apk-utils.js:28:9)
    at tryCatch (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
 Error: Error finding if app is installed. Original error: No device connected, cannot run adb shell command 'pm list packages io.appium.unlock'
    at Object.wrappedLogger.errorAndThrow (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/appium-support/lib/logging.js:69:13)
    at ADB.callee$0$0$ (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/appium-adb/lib/tools/apk-utils.js:28:9)
    at tryCatch (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>

2018-02-13T10:44:18.816Z - info: Appium err 2018-02-13 10:44:18:815 - [ADB] Error: Error getting device platform version. Original error: No device connected, cannot run adb shell command 'getprop ro.build.version.release'
    at Object.wrappedLogger.errorAndThrow (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/appium-support/lib/logging.js:69:13)
    at ADB.callee$0$0$ (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/appium-adb/lib/tools/adb-commands.js:89:9)
    at tryCatch (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
 Error: Error getting device platform version. Original error: No device connected, cannot run adb shell command 'getprop ro.build.version.release'
    at Object.wrappedLogger.errorAndThrow (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/appium-support/lib/logging.js:69:13)
    at ADB.callee$0$0$ (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/appium-adb/lib/tools/adb-commands.js:89:9)
    at tryCatch (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>

2018-02-13T10:44:18.828Z - info: Appium err 2018-02-13 10:44:18:827 - [MJSONWP] Encountered internal error running command: Error: Error getting device platform version. Original error: No device connected, cannot run adb shell command 'getprop ro.build.version.release'
    at Object.wrappedLogger.errorAndThrow (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/appium-support/lib/logging.js:69:13)
    at ADB.callee$0$0$ (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/appium-adb/lib/tools/adb-commands.js:89:9)
    at tryCatch (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>

2018-02-13T10:50:44.318Z - info: Appium on close  null
2018-02-13T10:50:44.322Z - info: You are not owner localhost:7405 => open STF 
2018-02-13T10:50:44.324Z - info: You are not owner localhost:7405 => open STF 
2018-02-13T12:50:49.619Z - info: Test execution started
2018-02-13T12:50:49.620Z - info: Got following options to run{"testName":"Clean Install","UDID":"cd21ccc5","port":4003,"systemPort":8203,"bpPort":6003,"desCaps":"{\n\"testName\":\"Clean Install\",\n\"groupTest\":false,\n\"desiredCapabilities\": {\n        \"platformName\": \"Android\",\n        \"deviceName\": \"Android\",\n        \"appPackage\":\"com.gorro.nothing\",\n        \"appActivity\":\"com.gorro.nothing.NothingActivity\",\n        \"fullReset\":false,\n        \"newCommandTimeout\":120000,\n        \"skipUnlock\":true\n      }\n\n}\n"}
2018-02-13T12:50:49.626Z - info: Trying to connect to openSTF with serial number cd21ccc5
2018-02-13T12:50:49.680Z - info: executing command adb connect  localhost:7409
2018-02-13T12:50:49.688Z - info: /home/trixo/Downloads/appium-1.8.0-beta3/build/lib/main.js -p 4003 -bp6003  --log-timestamp --log /home/trixo/Code/javaRewrite/log4003.txt
2018-02-13T12:50:49.688Z - info: Trying to create appium Server on port: 4003
2018-02-13T12:50:51.785Z - info: Appium server created on port: 4003
2018-02-13T12:50:51.894Z - info: Appium err 2018-02-13 12:50:51:893 - [AndroidDriver] Error: Device localhost:7409 was not in the list of connected devices
    at Object.wrappedLogger.errorAndThrow (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/appium-support/lib/logging.js:69:13)
    at Object.callee$0$0$ (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/appium-android-driver/lib/android-helpers.js:131:16)
    at tryCatch (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
 Error: Device localhost:7409 was not in the list of connected devices
    at Object.wrappedLogger.errorAndThrow (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/appium-support/lib/logging.js:69:13)
    at Object.callee$0$0$ (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/appium-android-driver/lib/android-helpers.js:131:16)
    at tryCatch (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>

2018-02-13T12:50:51.895Z - info: Appium err 2018-02-13 12:50:51:895 - [MJSONWP] Encountered internal error running command: Error: Device localhost:7409 was not in the list of connected devices
    at Object.wrappedLogger.errorAndThrow (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/appium-support/lib/logging.js:69:13)
    at Object.callee$0$0$ (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/appium-android-driver/lib/android-helpers.js:131:16)
    at tryCatch (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>

2018-02-13T12:50:51.910Z - info: You are not owner localhost:7409 => open STF 
2018-02-13T13:02:14.784Z - info: Appium on close  null
2018-02-13T13:02:14.808Z - info: You are not owner localhost:7409 => open STF 
2018-02-13T13:02:14.808Z - info: You are not owner localhost:7409 => open STF 
2018-02-14T14:01:09.252Z - info: Test execution started
2018-02-14T14:01:09.253Z - info: Got following options to run{"testName":"Clean Install","UDID":"cd21ccc5","port":4003,"systemPort":8203,"bpPort":6003,"desCaps":{"testName":"Clean Install","groupTest":false,"desiredCapabilities":{"platformName":"Android","deviceName":"Android","appPackage":"com.gorro.nothing","appActivity":"com.gorro.nothing.NothingActivity","fullReset":false,"newCommandTimeout":120000,"skipUnlock":true}}}
2018-02-14T14:01:09.261Z - info: Trying to connect to openSTF with serial number cd21ccc5
2018-02-14T14:01:09.317Z - info: executing command adb connect  localhost:7437
2018-02-14T14:01:09.323Z - info: /home/trixo/Downloads/appium-1.8.0-beta3/build/lib/main.js -p 4003 -bp6003  --log-timestamp --log /home/trixo/Code/javaRewrite/log4003.txt
2018-02-14T14:01:09.323Z - info: Trying to create appium Server on port: 4003
2018-02-14T14:01:11.620Z - info: Appium server created on port: 4003
2018-02-14T14:01:31.747Z - info: Appium err 2018-02-14 14:01:31:747 - [UiAutomator] UiAutomator exited unexpectedly with code null, signal SIGINT

2018-02-14T14:01:31.764Z - info: Appium err 2018-02-14 14:01:31:764 - [Logcat] Logcat terminated with code null, signal SIGINT

2018-02-14T14:01:31.789Z - info: Disconnected localhost:7437=> open STF 
2018-02-14T14:01:31.802Z - info: Running clean Install test with following paramters, appPackage: com.pointvoucher.playlondonpv activityName: com.unity3d.player.UnityPlayerActivity apkFile: /home/trixo/Code/javaRewrite/Tests/CleanInstall/apk/pl.apk
2018-02-14T14:01:31.824Z - info: You are not owner localhost:7437 => open STF 
2018-02-14T14:01:31.836Z - info: Appium err Unhandled rejection Error: Error executing adbExec. Original error: 'Command '/home/trixo/Android/Sdk/platform-tools/adb -P 5037 -s localhost\:7437 shell am force-stop com.gorro.nothing' exited with code 1'; Stderr: 'error: device 'localhost:7437' not found'; Code: '1'
    at ADB.execFunc$ (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/appium-adb/lib/tools/system-calls.js:317:13)
    at tryCatch (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>

2018-02-14T14:05:06.047Z - info: Test execution started
2018-02-14T14:05:06.048Z - info: Got following options to run{"testName":"Clean Install","UDID":"cd21ccc5","port":4003,"systemPort":8203,"bpPort":6003,"desCaps":{"testName":"Clean Install","groupTest":false,"desiredCapabilities":{"platformName":"Android","deviceName":"Android","appPackage":"com.gorro.nothing","appActivity":"com.gorro.nothing.NothingActivity","fullReset":false,"newCommandTimeout":120000,"skipUnlock":true}}}
2018-02-14T14:05:06.056Z - info: Trying to connect to openSTF with serial number cd21ccc5
2018-02-14T14:05:06.112Z - info: executing command adb connect  localhost:7437
2018-02-14T14:05:06.121Z - info: /home/trixo/Downloads/appium-1.8.0-beta3/build/lib/main.js -p 4003 -bp6003  --log-timestamp --log /home/trixo/Code/javaRewrite/log4003.txt
2018-02-14T14:05:06.121Z - info: Trying to create appium Server on port: 4003
2018-02-14T14:05:09.045Z - info: Appium server created on port: 4003
2018-02-14T14:05:43.609Z - info: Running clean Install test with following paramters, appPackage: com.pointvoucher.playlondonpv activityName: com.unity3d.player.UnityPlayerActivity apkFile: /home/trixo/Code/javaRewrite/Tests/CleanInstall/apk/pl.apk
2018-02-14T14:05:45.532Z - info: App exists in device => trying to remove
2018-02-14T14:05:51.696Z - info: App removed
2018-02-14T14:05:51.696Z - info: Installing app to device /home/trixo/Code/javaRewrite/Tests/CleanInstall/apk/pl.apk
2018-02-14T14:06:45.496Z - info: starting package : com.pointvoucher.playlondonpv with activity name: com.unity3d.player.UnityPlayerActivity
2018-02-14T14:06:50.346Z - info: Running fnPermission with number of repeats: 5 and value: true
2018-02-14T14:06:51.752Z - info: Found permission button going to click #0
2018-02-14T14:06:51.753Z - info: Running click event : Click on permission button with 5repets
2018-02-14T14:06:51.753Z - info: Looking for image on screen:Click on permission button with 5 repeats 
2018-02-14T14:06:51.753Z - info: Running delay for : 0
2018-02-14T14:06:51.755Z - info: Running delay for : 0
2018-02-14T14:06:52.964Z - info: Found image on screen: Click on permission button
2018-02-14T14:06:53.370Z - info: clicked on : Click on permission button with following coordinates x=438 y=556.5
2018-02-14T14:06:53.370Z - info: Looking for image on screen:Loading screen with 20 repeats 
2018-02-14T14:06:53.370Z - info: Running delay for : 6000
2018-02-14T14:06:59.371Z - info: Running delay for : 2000
2018-02-14T14:07:04.647Z - info: Running delay for : 2000
2018-02-14T14:07:07.779Z - info: Running delay for : 2000
2018-02-14T14:07:10.619Z - info: Running delay for : 2000
2018-02-14T14:07:13.678Z - info: Running delay for : 2000
2018-02-14T14:07:16.417Z - info: Running delay for : 2000
2018-02-14T14:07:19.222Z - info: Running delay for : 2000
2018-02-14T14:07:22.260Z - info: Running delay for : 2000
2018-02-14T14:07:26.112Z - info: Found image on screen: Loading screen
2018-02-14T14:07:26.112Z - info: Test:Clean Install[FINISHED]
2018-02-14T14:07:26.142Z - info: Disconnected localhost:7437=> open STF 
2018-02-14T14:07:26.143Z - info: Appium err 2018-02-14 14:07:26:143 - [Logcat] Logcat terminated with code 0, signal null

2018-02-14T14:07:26.145Z - info: Appium err 2018-02-14 14:07:26:144 - [UiAutomator] UiAutomator exited unexpectedly with code 0, signal null

2018-02-14T14:07:26.203Z - info: Appium err 2018-02-14 14:07:26:203 - [Appium] Had trouble ending session 37aff8a1-979b-47eb-9048-dd79246c02a6: Error executing adbExec. Original error: 'Command '/home/trixo/Android/Sdk/platform-tools/adb -P 5037 -s localhost\:7437 shell am force-stop com.gorro.nothing' exited with code 1'; Stderr: 'error: device 'localhost:7437' not found'; Code: '1'

2018-02-14T14:07:26.226Z - info: Appium err 2018-02-14 14:07:26:225 - [MJSONWP] Encountered internal error running command: Error: Error executing adbExec. Original error: 'Command '/home/trixo/Android/Sdk/platform-tools/adb -P 5037 -s localhost\:7437 shell am force-stop com.gorro.nothing' exited with code 1'; Stderr: 'error: device 'localhost:7437' not found'; Code: '1'
    at ADB.execFunc$ (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/appium-adb/lib/tools/system-calls.js:317:13)
    at tryCatch (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>

2018-02-14T14:07:26.242Z - info: Appium err Unhandled rejection Error: Error executing adbExec. Original error: 'Command '/home/trixo/Android/Sdk/platform-tools/adb -P 5037 -s localhost\:7437 shell am force-stop com.gorro.nothing' exited with code 1'; Stderr: 'error: device 'localhost:7437' not found'; Code: '1'
    at ADB.execFunc$ (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/appium-adb/lib/tools/system-calls.js:317:13)
    at tryCatch (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>

2018-02-14T14:11:17.480Z - info: You are not owner localhost:7437 => open STF 
2018-02-14T14:11:17.481Z - info: You are not owner localhost:7437 => open STF 
2018-02-14T14:11:17.482Z - info: Appium on close  null
2018-02-14T14:45:45.617Z - info: Test execution started
2018-02-14T14:45:45.618Z - info: Got following options to run{"testName":"Clean Install","UDID":"localhost:7417","port":4003,"systemPort":8203,"bpPort":6003,"desCaps":{"testName":"Clean Install","groupTest":false,"desiredCapabilities":{"platformName":"Android","deviceName":"Android","appPackage":"com.gorro.nothing","appActivity":"com.gorro.nothing.NothingActivity","fullReset":false,"newCommandTimeout":120000,"skipUnlock":true}}}
2018-02-14T14:45:45.625Z - info: Trying to connect to openSTF with serial number localhost:7417
2018-02-14T14:45:45.670Z - info: You are not owner undefined => open STF 
2018-02-14T15:10:48.262Z - info: Test execution started
2018-02-14T15:10:48.263Z - info: Got following options to run{"testName":"Clean Install","UDID":"emulator-5554","port":4003,"systemPort":8203,"bpPort":6003,"desCaps":{"testName":"Clean Install","groupTest":false,"desiredCapabilities":{"platformName":"Android","deviceName":"Android","appPackage":"com.gorro.nothing","appActivity":"com.gorro.nothing.NothingActivity","fullReset":false,"newCommandTimeout":120000,"skipUnlock":true}}}
2018-02-14T15:10:48.270Z - info: Trying to connect to openSTF with serial number emulator-5554
2018-02-14T15:10:48.341Z - info: executing command adb connect  localhost:7417
2018-02-14T15:10:48.370Z - info: /home/trixo/Downloads/appium-1.8.0-beta3/build/lib/main.js -p 4003 -bp6003  --log-timestamp --log /home/trixo/Code/javaRewrite/log4003.txt
2018-02-14T15:10:48.370Z - info: Trying to create appium Server on port: 4003
2018-02-14T15:11:23.298Z - info: Appium server created on port: 4003
2018-02-14T15:11:28.471Z - info: Running clean Install test with following paramters, appPackage: com.pointvoucher.playlondonpv activityName: com.unity3d.player.UnityPlayerActivity apkFile: /home/trixo/Code/javaRewrite/Tests/CleanInstall/apk/pl.apk
2018-02-14T15:11:28.655Z - info: App exists in device => trying to remove
2018-02-14T15:11:29.481Z - info: App removed
2018-02-14T15:11:29.481Z - info: Installing app to device /home/trixo/Code/javaRewrite/Tests/CleanInstall/apk/pl.apk
2018-02-14T15:11:39.606Z - info: starting package : com.pointvoucher.playlondonpv with activity name: com.unity3d.player.UnityPlayerActivity
2018-02-14T15:11:40.534Z - info: Running fnPermission with number of repeats: 5 and value: true
2018-02-14T15:11:41.069Z - info: Found permission button going to click #0
2018-02-14T15:11:41.069Z - info: Running click event : Click on permission button with 5repets
2018-02-14T15:11:41.069Z - info: Looking for image on screen:Click on permission button with 5 repeats 
2018-02-14T15:11:41.069Z - info: Running delay for : 0
2018-02-14T15:11:41.071Z - info: Running delay for : 0
2018-02-14T15:11:41.520Z - info: Found image on screen: Click on permission button
2018-02-14T15:11:41.659Z - info: clicked on : Click on permission button with following coordinates x=411 y=573.5
2018-02-14T15:11:41.659Z - info: Looking for image on screen:Loading screen with 20 repeats 
2018-02-14T15:11:41.660Z - info: Running delay for : 6000
2018-02-14T15:11:47.660Z - info: Running delay for : 2000
2018-02-14T15:11:50.179Z - info: Running delay for : 2000
2018-02-14T15:11:52.804Z - info: Found image on screen: Loading screen
2018-02-14T15:11:52.804Z - info: Test:Clean Install[FINISHED]
2018-02-14T15:11:52.851Z - info: Disconnected localhost:7417=> open STF 
2018-02-14T15:11:52.852Z - info: Appium err 2018-02-14 15:11:52:852 - [Logcat] Logcat terminated with code 0, signal null

2018-02-14T15:11:52.853Z - info: Appium err 2018-02-14 15:11:52:853 - [UiAutomator] UiAutomator exited unexpectedly with code 0, signal null

2018-02-14T15:11:53.207Z - info: Appium err Unhandled rejection Error: Error executing adbExec. Original error: 'Command '/home/trixo/Android/Sdk/platform-tools/adb -P 5037 -s localhost\:7417 shell am force-stop com.gorro.nothing' exited with code 1'; Stderr: 'error: device 'localhost:7417' not found'; Code: '1'
    at ADB.execFunc$ (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/appium-adb/lib/tools/system-calls.js:317:13)
    at tryCatch (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>

2018-02-14T15:11:53.209Z - info: Appium err 2018-02-14 15:11:53:209 - [Appium] Had trouble ending session 2c993869-7e44-489e-94ba-018867d325ac: Error executing adbExec. Original error: 'Command '/home/trixo/Android/Sdk/platform-tools/adb -P 5037 -s localhost\:7417 shell input keyevent 3' exited with code 1'; Stderr: 'error: device 'localhost:7417' not found'; Code: '1'

2018-02-14T15:11:53.210Z - info: Appium err 2018-02-14 15:11:53:210 - [MJSONWP] Encountered internal error running command: Error: Error executing adbExec. Original error: 'Command '/home/trixo/Android/Sdk/platform-tools/adb -P 5037 -s localhost\:7417 shell input keyevent 3' exited with code 1'; Stderr: 'error: device 'localhost:7417' not found'; Code: '1'
    at ADB.execFunc$ (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/appium-adb/lib/tools/system-calls.js:317:13)
    at tryCatch (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/home/trixo/Downloads/appium-1.8.0-beta3/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>

2018-02-14T15:15:02.055Z - info: You are not owner localhost:7417 => open STF 
2018-02-14T15:15:02.060Z - info: You are not owner localhost:7417 => open STF 
2018-02-14T15:15:02.510Z - info: Appium on close  null
